### ISSUE TITLE
Starry Night?

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/after-dark-css#4]
Just logging an email request I got:

> I wanted to personally thank you for crafting the After dark in CSS page.
> I was wondering if there were any chance you might create a"starry night" module?

Starry night would be tough, since there's not a good way to add run-time randomness to CSS animations. Still, I think there are ways to mimic the look and feel, and it would be cool to see one in action. I not planning on attempting this at the moment, but I'll happily merge a contribution if somebody wants to give it a shot.

**Comment by jmfergeau** [comment]
I think this guy actually did it: https://github.com/ldtcooper/starry-night
Not the 100% exact same deal but close enough to get an eye on it ^^

**Comment by bryanbraun** [comment]
Nice find, and thanks for sharing. 😄

I think I'm going to go ahead and close this issue, since it's been years and I'm not expecting to find a CSS-only solution for this. 👍
