### ISSUE TITLE
Random Quotes screensaver

### ISSUE THREAD

**Issue by jmfergeau** [bryanbraun/after-dark-css#7]
Hey again. ^^

Actually your project motivated me to remake an old After Dark screensaver I used to like when I was a kid. I don't remember the exact name but I prefectly remembered the behavior.

It was a black screen with, at fixed interval, a random quote displays. You could put your own quotes, as many as you want, and you could choose the style and colors of the borders around the quotes. I don't know if you ever seen that one.

Anyway, I just made it and published it on my gitlab. Feel free to include it in your project! ;)
[https://gitlab.com/maxlefou/adquotes](https://gitlab.com/maxlefou/adquotes)

Just like the original screensaver, quotes and borders styles are editable easily, just by editing a file named options.js.

[You can see it in action here](https://maxlefou.gitlab.io/adquotes/).

**Comment by bryanbraun** [comment]
Hey, I just took a look. This is great!

I probably won't add it to my repo, since all of mine have this arbitrary constraint of using only CSS. Either way, I think it's a great project... thanks for sharing it with me. :)
